import type {Metadata} from "next";
import {Inter} from 'next/font/google';
import "./globals.css";
import {MSWComponent} from "@/app/_component/MSWComponent";
import AuthSession from "@/app/_component/AuthSession";

const inter = Inter({subsets: ['latin']})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//? layout를 적용하지 않는 페이지도 존재하기 떄문에 예외 처리가 필요
export default function RootLayout({
    children,  // 컴포넌트를 프랍스로 넘겨받아 사용한다
  }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
    <body className={inter.className}>
    {/* msw 모킹서버 세팅 완료 */}
    <MSWComponent/>
    {/* 클라이언트 컴포넌트에서 세션정보 꺼내쓸 수 있도록 설정 */}
    <AuthSession>
      {children}
    </AuthSession>
    </body>
    </html>
  );
}
