import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//? layout를 적용하지 않는 페이지도 존재하기 떄문에 예외 처리가 필요
export default function RootLayout({
  children,  // 컴포넌트를 프랍스로 넘겨받아 사용한다
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
